version: '3'
services:
  app:
    build: .
    tty: true
    ports:
      - 8000:8000
      - 5555:5555
    volumes:
      - .:/TeamScheduler 
    depends_on:
      - psql

      
  psql:
    image: postgres:14.2
    tty: true
    ports:
      - 5432:5432
    volumes:
      - psql:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  TeamScheduler:
  psql:
    external: true